version: '3.8'

services:

  db:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    # image: leyan:latest
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    ports:
     - "8000:8000"
    command: >
      bash -c "python manage.py migrate &&
      python manage.py makemigrations &&
      python manage.py makemigrations product &&
      python manage.py makemigrations shop &&
      python manage.py makemigrations sale &&
      python manage.py makemigrations forecast &&
      python manage.py makemigrations user &&
      python manage.py migrate &&
      python manage.py parse_shops &&
      python manage.py parse_product &&
      python manage.py collectstatic --no-input &&
      gunicorn --bind 0:8000 leyan.wsgi"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - db
    env_file:
      - ./.env

  # frontend:
  #   image: frontend:latest
  #   volumes:
  #     - ../frontend/:/app/result_build/
  #   depends_on:
  #     - backend

  # ml:
  #   build:
  #     context: ../ml
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - backend
  #     - frontend

  nginx:
    image: nginx:1.23.4-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      # - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
