# Generated by Django 3.2.18 on 2023-10-01 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="division",
            name="division_code_id",
        ),
        migrations.RemoveField(
            model_name="location",
            name="type_loc_id",
        ),
        migrations.RemoveField(
            model_name="size",
            name="type_size_id",
        ),
        migrations.AddField(
            model_name="division",
            name="division_id",
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AddField(
            model_name="location",
            name="loc_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="size",
            name="size_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="city",
            name="city_id",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="format",
            name="type_format_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="shop",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop",
                to="shop.city",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="division",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop",
                to="shop.division",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="is_active",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "НЕТ"), (1, "ДА")]
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="loc",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop",
                to="shop.location",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="size",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop",
                to="shop.size",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="store",
            field=models.CharField(
                max_length=150, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="type_format",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop",
                to="shop.format",
            ),
        ),
    ]
