version: '3.8'

services:

  db:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    # image: backend:latest
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    command: >
      bash -c "python manage.py migrate &&
      python manage.py createsuperuser &&
      gunicorn --bind 0:8000 leyan.wsgi"
    depends_on:
      - db
    env_file:
      - ./.env

  # frontend:
  #   image: frontend:latest
  #   volumes:
  #     - ../frontend/:/app/result_build/
  #   depends_on:
  #     - backend

  nginx:
    image: nginx:1.23.4-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf/default.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/build:/usr/share/nginx/html/
      # - ../docs/:/usr/share/nginx/html/api/docs/
      # - static_value:/var/html/back-static/
      # - media_value:/var/html/back-media/
    depends_on:
      - backend
      # - frontend

volumes:
  postgres_data:
  # static_value:
  # media_value:
