# Generated by Django 3.2.18 on 2023-10-02 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "__first__"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "sales_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "НЕТ"), (1, "ДА")]
                    ),
                ),
                ("sales_units", models.PositiveSmallIntegerField()),
                ("sales_units_promo", models.PositiveSmallIntegerField()),
                (
                    "sales_rub",
                    models.DecimalField(decimal_places=10, max_digits=19),
                ),
                (
                    "sales_rub_promo",
                    models.DecimalField(
                        decimal_places=10, default=0, max_digits=19
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale",
                        to="product.product",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale",
                        to="shop.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продажи",
                "verbose_name_plural": "Продажи",
            },
        ),
    ]
