# Generated by Django 4.2.6 on 2023-10-20 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "sales_type",
                    models.IntegerField(
                        choices=[(0, "нет"), (1, "да")],
                        verbose_name="Тип продажи",
                    ),
                ),
                (
                    "sales_units",
                    models.IntegerField(verbose_name="Продажа ед."),
                ),
                (
                    "sales_units_promo",
                    models.IntegerField(verbose_name="Продажа ед. промо"),
                ),
                (
                    "sales_rub",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=19,
                        verbose_name="Продажа в руб.",
                    ),
                ),
                (
                    "sales_rub_promo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=19,
                        verbose_name="Продажа в руб. промо",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.shop",
                        verbose_name="Магазин",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продажи",
                "verbose_name_plural": "Продажи",
                "default_related_name": "sales",
            },
        ),
    ]
