# Generated by Django 3.2.18 on 2023-10-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "sales_type",
                    models.IntegerField(choices=[(0, "нет"), (1, "да")]),
                ),
                ("sales_units", models.IntegerField()),
                ("sales_units_promo", models.IntegerField()),
                (
                    "sales_rub",
                    models.DecimalField(decimal_places=2, max_digits=19),
                ),
                (
                    "sales_rub_promo",
                    models.DecimalField(decimal_places=2, max_digits=19),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="product.product",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="shop.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продажи",
                "verbose_name_plural": "Продажи",
            },
        ),
    ]
