# Generated by Django 3.2.18 on 2023-10-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=150, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=150, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=150, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "sku",
                    models.CharField(
                        max_length=150,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Артикул",
                    ),
                ),
                (
                    "uom",
                    models.IntegerField(
                        choices=[(1, "шт."), (17, "вес")],
                        verbose_name="Ед. изм.",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product",
                        to="product.category",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product",
                        to="product.group",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product",
                        to="product.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
