# Generated by Django 3.2.18 on 2023-10-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_auto_20230930_2329"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="cat_id",
            field=models.CharField(
                max_length=150, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="group_id",
            field=models.CharField(
                max_length=150, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                max_length=150,
                primary_key=True,
                serialize=False,
                verbose_name="артикул",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="uom",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "ШТ"), (17, "ВЕС")], verbose_name="ед. изм."
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="subcat_id",
            field=models.CharField(
                max_length=150, primary_key=True, serialize=False
            ),
        ),
    ]
