name: CI/CD для LeYan

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version:  '3.10'

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install -r backend/requirements.txt

    - name: Test with flake8
      run: |
        python -m flake8
